name: senseless_dough
description: This library provides widgets that can be used to create a smooshy user interface. without sensors
version: 2.0.0
repository: https://github.com/cyberpwnn/senseless_dough
homepage: https://github.com/josiahsrc/dough
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  provider: ^6.1.1
  vector_math: ^2.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
